sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t abhilasha1307/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true abhilasha1307/react-test npm test

after_success: 
  - docker build -t abhilasha1307/multi-client ./client
  - docker build -t abhilasha1307/multi-nginx ./nginx
  - docker build -t abhilasha1307/multi-server ./server
  - docker build -t abhilasha1307/multi-worker ./worker
