sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t abhilasha1307/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true abhilasha1307/react-test npm test

after_success: 
  - docker build -t abhilasha1307/multi-client ./client
  - docker build -t abhilasha1307/multi-nginx ./nginx
  - docker build -t abhilasha1307/multi-server ./server
  - docker build -t abhilasha1307/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push them to docker hub
  - docker push abhilasha1307/multi-client
  - docker push abhilasha1307/multi-nginx
  - docker push abhilasha1307/multi-server
  - docker push abhilasha1307/multi-worker

